### ISSUE TITLE
maud_lints fails to compile on rustc 1.21.0-nightly (f25c2283b 2017-08-15)

### ISSUE THREAD

**Issue by lfairy** [lfairy/maud#99]
```
error[E0308]: mismatched types
  --> maud_lints/src/doctype.rs:33:53
   |
33 |             let def_id = cx.tables.qpath_def(qpath, path_expr.id).def_id();
   |                                                     ^^^^^^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
   |
   = note: expected type `rustc::hir::HirId`
              found type `syntax::ast::NodeId`
```
